site_name: Databricks Best Practices
nav:
  - Home: index.md
  - Admin:
    - Cluster Configuration: 'Admin/cluster_configuration.md'
    - Notebook Usage: 'Admin/notebook.md'
  - SQL:
    - Queries: 'SQL/queries.md'
    - SQL Warehouses: 'SQL/warehouses.md'
  - Data Engineering:
    - Delta Lake: 'DE/delta_lake.md'
    - Delta Live Tables: 'DE/dlt.md'
    - Workflows: 'DE/workflows.md'
  - Machine Learning:
    - MLOps: 'ML/mlops.md'
    - Deep Learning: 'ML/deep_learning.md'
    - Hyperparameter tuning with Hyperopt: 'ML/hyperparameter_tuning.md'
theme:
  name: mkdocs
  nav_style: dark
  