site_name: Databricks Best Practices
nav:
  - Home: index.md
  - Data Engineering:
    - Delta Lake: 'DE/delta_lake.md'
    - Workflows: 'DE/workflows.md'
    - Delta Live Tables Best Practices: 'DE/dlt.md'
    - Delta Live Tables Cookbook: 'DE/dlt_cookbook.md'
    - Clone: 'DE/clone.md'
  - Machine Learning:
    - MLOps: 'ML/mlops.md'
    - Deep Learning: 'ML/deep_learning.md'
    - Hyperparameter tuning with Hyperopt: 'ML/hyperparameter_tuning.md'
  - SQL:
    - SQL Warehouses: 'SQL/warehouses.md'
    - Queries: 'SQL/queries.md'
  - Unity Catalog & Admin:
    - Unity Catalog: 'UC/uc.md'
    - Identity: 'UC/identity.md'
  - Cluster Management:
    - Cluster Configuration: 'Cluster/cluster_configuration.md'
    - Pools: 'Cluster/pools.md'
  - Development:
    - CI/CD: 'Dev/cicd.md'
    - Notebook Usage: 'Dev/notebook.md'
theme:
  name: mkdocs
  nav_style: dark
  